// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAls7269DUP4wcTCquUOnRl86pywXcfcGA',
    appId: '1:776958597870:web:e0cd9cb5e13e6945b331ff',
    messagingSenderId: '776958597870',
    projectId: 'instaclone-8b4c3',
    authDomain: 'instaclone-8b4c3.firebaseapp.com',
    storageBucket: 'instaclone-8b4c3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCEYg5juojZeXOxc9QjbnuRBIJMqhPETs',
    appId: '1:776958597870:android:5a9520a89361cfe0b331ff',
    messagingSenderId: '776958597870',
    projectId: 'instaclone-8b4c3',
    storageBucket: 'instaclone-8b4c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHIvTgj4ndJVcdyMKYFR1sombXTtx9NBE',
    appId: '1:776958597870:ios:1a702889cc3b7542b331ff',
    messagingSenderId: '776958597870',
    projectId: 'instaclone-8b4c3',
    storageBucket: 'instaclone-8b4c3.appspot.com',
    iosBundleId: 'com.example.instaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHIvTgj4ndJVcdyMKYFR1sombXTtx9NBE',
    appId: '1:776958597870:ios:1a702889cc3b7542b331ff',
    messagingSenderId: '776958597870',
    projectId: 'instaclone-8b4c3',
    storageBucket: 'instaclone-8b4c3.appspot.com',
    iosBundleId: 'com.example.instaClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAls7269DUP4wcTCquUOnRl86pywXcfcGA',
    appId: '1:776958597870:web:b184abbe757ee4efb331ff',
    messagingSenderId: '776958597870',
    projectId: 'instaclone-8b4c3',
    authDomain: 'instaclone-8b4c3.firebaseapp.com',
    storageBucket: 'instaclone-8b4c3.appspot.com',
  );
}
